version: '3.8'

services:
  # PostgreSQL Database Service
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopshield
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Spring Boot Backend Service
  spring-backend:
    container_name: spring-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/shopshield
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    restart: on-failure

  # FastAPI OCR Microservice
  ocr-service:
    container_name: ocr-service
    build:
      context: ./ocr-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure

  # FastAPI Computer Vision (Fake Product) Microservice
  cv-service:
    container_name: cv-service
    build:
      context: ./cv-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: on-failure

  # React Frontend Service (served with Nginx)
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Nginx default port is 80
    depends_on:
      - spring-backend
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local